package model.planner;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.TreeMap;
import model.date.PlannerDate;
import model.theme.PlannerTheme;
//TODO add exceptions that should be thrown for invalid arguments
/**
 * An IPlannerModel implementation that represents a simple planner. It uses
 * the PlannerTheme class as the theme and the PlannerDate class as the
 * date.
 */
public class SimplePlannerModel implements IPlannerModel<PlannerTheme, PlannerDate> {
  // for every date there is a list of tasks.
  private TreeMap<PlannerDate, List<String>> taskMap;
  private int totalPoints;
  private String userName;
  private List<PlannerTheme> themeList;
  private PlannerTheme currentTheme;

  // should we have a list of locked themes?

  // the themes should be generated by the model and not be able to be accessed
  // until the correct number of points are earned

  /**
   * Initializes a new simple planner.
   */
  public SimplePlannerModel() {
    this.taskMap = new TreeMap<>();
    this.totalPoints = 0;
    this.userName = "Enter your name!";
    this.themeList = new ArrayList<>(); // set a default theme?
  }

  @Override
  public void addTask(String task, PlannerDate date) throws IllegalArgumentException {
    if (task == null || date == null) {
      throw new IllegalArgumentException("task and date must be non-null");
    }
    // check if the date already exists
    if (this.taskMap.containsKey(date)) {
      // add the task to the list of tasks at the given date
      List<String> newValueList = new ArrayList<>(this.taskMap.get(date));
      newValueList.add(task);
      this.taskMap.put(date, newValueList);
    } else {
      // put the date as a new key in the tree map
      this.taskMap.put(date, Arrays.asList(new String[]{task}));
    }
  }

  @Override
  public List<String> getTasks() {
    // list of values
    List<List<String>> copyValues = new ArrayList();
    copyValues.addAll(taskMap.values());

    // flatten the list of list of strings
    List newList = new ArrayList();
    for (List<String> los : copyValues) {
      newList.addAll(los);
    }

    // returns a copy of the tasks as one list
    // in the order of their date
    return newList;
  }

  @Override
  public void removeTask(String task, PlannerDate date) throws IllegalArgumentException {
    if (task == null || date == null) {
      throw new IllegalArgumentException("task and date must be non-null");
    }
    // first check that the date exists, then check if the task exists
    if (!this.taskMap.containsKey(date)) {
      throw new IllegalArgumentException("date does not exist");
    } else {
      // check that the task exists
      if (this.taskMap.get(date).contains(task)) {
        List<String> newValueList = new ArrayList<>(this.taskMap.get(date));
        newValueList.remove(task);
        this.taskMap.put(date, newValueList);
      } else {
        throw new IllegalArgumentException("task does not exist");
      }
    }
  }

  @Override
  public void moveTask(String task, PlannerDate initialDate, PlannerDate newDate) throws
      IllegalArgumentException {
    if (task == null || initialDate == null || newDate == null) {
      throw new IllegalArgumentException("task and dates must be non-null");
    }

    // check that the initialDate exists
    if (!this.taskMap.containsKey(initialDate)) {
      throw new IllegalArgumentException("initialDate does not exist");
    } else {
      // check that the task exists
      if (this.taskMap.get(initialDate).contains(task)) {
        // remove from initial date
        List<String> newValueList = new ArrayList<>(this.taskMap.get(initialDate));
        newValueList.remove(task);
        this.taskMap.put(initialDate, newValueList);

        // check if the newDate already exists or not
        if (this.taskMap.containsKey(newDate)) {
          // add the task to the date key that already exists
          List<String> newValueList2 = new ArrayList<>(this.taskMap.get(newDate));
          newValueList2.remove(task);
          this.taskMap.put(newDate, newValueList2);
        } else {
          // create the new date key and add the task
          this.taskMap.put(newDate, Arrays.asList(new String[]{task}));
        }
      } else {
        throw new IllegalArgumentException("task does not exist");
      }
    }
  }

  @Override
  public void addPoints(int points) {
    if (points <= 0) {
      throw new IllegalArgumentException("points must be positive");
    }
    this.totalPoints+=points;
  }

  @Override
  public int getTotalPoints() {
    return this.totalPoints;
  }

  @Override
  public void removePoints(int points) {
    if (points <= 0 || points > this.totalPoints) {
      throw new IllegalArgumentException("points must be positive and not exceed "
          + "the model's total number of points");
    }
    this.totalPoints-=points;
  }

  @Override
  public String getUserName() {
    return this.userName;
  }

  @Override
  public void setUserName(String name) throws IllegalArgumentException {
    if (name == null) {
      throw new IllegalArgumentException("name must be non-null");
    }
    this.userName = name;
  }

  @Override
  public List<PlannerTheme> getThemes() {
    // return a copy of the list of unlocked themes
    List copy = new ArrayList();
    copy.addAll(this.themeList);
    return copy;
  }

  @Override
  public void addTheme(PlannerTheme theme) {
    if (theme == null) {
      throw new IllegalArgumentException("theme must be non-null");
    }
    this.themeList.add(theme);
  }

  @Override
  public void setTheme(PlannerTheme theme) {
    if (theme == null) {
      throw new IllegalArgumentException("theme must be non-null");
    }
    this.currentTheme=theme;
  }

  @Override
  public List<String> getTasksInDay(PlannerDate date) throws IllegalArgumentException {
    if (date == null) {
      throw new IllegalArgumentException("the date must be non-null");
    }
    // check that the date is in the taskMap? if it isn't it should just return empty?coooo

    // return a copy of the tasks in a given day
    List copy = new ArrayList();
    copy.addAll(this.taskMap.get(date));
    return copy;
  }
}
